### ISSUE TITLE
Create a Freestyle Jenkins Project

### ISSUE THREAD

**Issue by 1201172** [1201172/ddd-forum-odsoft-1180658-1181600-1200615-1201172#10]

**Comment by 1200615-JoaoMoreira** [comment]
No Jenkins, primeiramente fazer build e verificar que terminou com sucesso.

Ir a Configurar,verificar que nao tem NodeJS instalado e, portanto, confirmar que versão do NodeJs é para instalar. Providenciar a versão do Nodejs que queremos utilizar (neste caso, será a versão 12.22.12). Aplicar as alterações.

Fazer build novamente e verificar que a build terminou com sucesso.

voltar a Configurar e, em Source Code Management, alterar a aopção para git e colar o URL do repositório do github.

Fazer build novamente e verificar que terminou com sucesso e que as pastas do repositório foram adicionadas ao workspace do Jenkins.
